- bureau/class/m_err.php
Logfile did not contain the IP address of the client in case of error. This can be usefull to filter out attacks, such as login bruteforce.
> log entries for error and log both log IP address

- jessie/alternc.install
mails submitted over smtp, and not sent via webmail was not being signed by opendkim because the external ip of the hosting server was missing from the trustedhosts file
> fix opendkim signing for mails submitted over the network

- ssl/alternc-ssl.install.php
PHP Warning:  mkdir(): File exists in /usr/lib/alternc/install.d/alternc-ssl on line 12
> Avoid a warning if directory exists

- bureau/class/config.php
Should be `isset($_SERVER["HTTP_X_FORWARDED_PROTO"])` and not `!isset($_SERVER["HTTP_X_FORWARDED_PROTO"])`
Avoid a notice : 
`PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/alternc/panel/class/config.php on line 170`
> Error on isset for X_FORWARDED_PROTO

- ssl/alternc-ssl.install.php
Empêchait la création du template roundcube-ssl fix #80 normalement
> Une parenthèse fermante manquante dans la requète

- bureau/class/m_hta.php
Current error messages that are shown and logged when a problem occurs
when creating htaccess and htpasswd files for a protected dir are really
not helpful.
The messages don't even mention which file caused the error.
Sometimes when the files can't be created, it's not because they're
already present, for example when there's a permission error.
Also we've already verified that they are absent with file_exists so
the current error message is not accurate at all!
To empower users, we need to give them more details about the error. For
that we want to show the error that the file creation logged itself.
Finally, we've already verified that the htacces file already exists, so
there's no point in using touch beforehand. We should just let fopen try
to create the file and report whatever went …
> Protected dir creation error messages are not helpful.

- src/functions_hosting.sh
> Corrigé le répertoire de validation des templates avant effacement

- src/update_domains.sh
If VHOST_DIR is a symbolic link to another folder, no files will be found,
resulting in an empty vhosts_all.conf. A trailing slash ensures find will
properly resolve the symbolic link before searching.
> Fix #257: Add trailing slash to VHOST_DIR when building vhosts_all.conf

- debian/alternc-roundcube.postinst
- roundcube/roundcube-install
- roundcube/templates/apache2/roundcube.conf
Roundcube vhosts run as www-data:www-data, but alternc.install was changing the ownership of the configuration to alternc-roundcube causing the application to be unable to read the configuration and load.
Also removed creation of the alternc-roundcube user during install of alternc-roundcube as it's not used.
@see #285
> Fix roundcube webmail access

- etc/alternc/templates/apache2/vhost-both.conf
- etc/alternc/templates/apache2/vhost-http.conf
- etc/alternc/templates/apache2/vhost-https.conf
Add one php_admin_value in vhosts templates to configure the value returned by get_sys_temp_dir().
This INI setting exists from PHP 5.4+ (so this patch should be reverted for Debian lower than Jessie)
> add php config for sys_temp_dir in vhost templates (for PHP 5.4+)

- etc/alternc/templates/opendkim.conf
- install/alternc.install
The default configuration in stretch doesn't work very well and
needs a couple of tweaks. This will generate the service files and
make sure opendkim is run as the opendkim user instead of root.
The alternc opendkim.conf template is updated so that the connection
can be made locally through a socket.
> Fix #233: Generate opendkim configuration in stretch when alternc.install is run

- bureau/class/m_ssl.php
The sslcsr is just set to an empty string so that the query works properly.
Without it, queries fail since sslcsr does not have a default value set.
Improved the detail of the messages logged during the failure of that query as well.
> Fixes #370: Fix insert query failure during import_cert

- bureau/class/m_admin.php
- bureau/class/m_mysql.php
- install/alternc.install
Fixes single-signon errors from not being able to access PhpMyAdmin lib files from the panel, and having the wrong blowfish secret length.
The main PhpMyAdmin link in the admin panel uses the single-signon script now (no longer depends on already have received a cookie in the past), and when a user has no databases, they are returned with an error instead.
The last thing left to finish here is to find out why in some cases (@quenenni's 1st point in #335), the auto-generated entries aren't added to phpmyadmin.inc.php.
> Fixes #335: Fix PHPMyAdmin Single-signon errors

- bureau/class/m_piwik.php
Two changes to fix some issues with Matomo integration
* Store the hash of the matomo user's password instead of a fixed string (Fixes part of #260)
* Request an unlimited number of results for the site lists. By default Matomo applies a limit of 100 results on API endpoints which return arrays.
Thanks,
Kienan
> Matomo integration fixes

- debian/control
This follows the Debian policy on using Breaks when moving files from one
package to another.
@see https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts
If apt/apt-get are used to install the new package, it will know to automatically
remove alternc-ssl (or alternc-admintools) instead of refusing to proceed at all.
Refs #374
> Use Breaks instead of Conflicts with alternc-ssl and alternc-admintools

- README.md
The upgrade process will delete ssl and mixssl sub domains provided previously by the alternc-ssl package. This adds a brief set of instructions for working around the issue to the readme file.
Refs #374
> Add a notice in the README about upgrading from 3.3.11 to 3.5.x

- bureau/admin/ip_main.php
As requested, here is the PR that fixes #326, a minor detail in the form `Add an IP or a networks`, in which the titles of the fields are inverted.
> Fix #326 - Minor detail in form

- api/panel/bootstrap.php
Without this global instance, nothing works during the bootstrap: all
calls to log() crash because the instance does not exist.
closes: #419
> API: instantiate m_message for logging

- bureau/class/m_bind.php
hook_updatedomains_dns_{add,del} have their return values checked in
m_dom::update_domains() to set the dns_result column.
When no return value is specified, the value is actually NULL and doesn't
get mapped to an integer value that is expected by the dns_result column.
As a result, the query fails silently and the DNS_ACTION column is never
updated. This causes update_domains to retry the same modification on
every run.
Note: 0/1 is used instead of TRUE/FALSE since the original code expects
integer return values from a shell script.
> Fix #413: Add return values for bind update domains hooks

- bureau/admin/index.php
- bureau/admin/mem_param.php
- bureau/admin/request_reset.php
- bureau/admin/reset.php
- bureau/class/m_mem.php
Allows a user to request a one-time login link send via e-mail. Once used, the user is logged in and is able to change their password once without requiring the old password to be submitted.
Highly inspired from how Drupal handles password reset with one-time login links.
Closes #102
> Issue #102: Add password reset via one-time login link

- bureau/class/m_mail.php
Fixes #341
When applying LIMIT X, Y the ordering before the limit and offset do
not seem to be guaranteed. For example, if you have a large number of
e-mail addresses, and you page between the same e-mail address can appear twice.
The case where this was happening there were 2-3 mail boxes and ~90 aliases.
I'm not sure if this tied somehow to the database version used, but making the
desired ordering explicit ensures that all mails will eventually be shown and
shouldn't be shown twice.
> Order enumerated mails for a domain by ascending alphabetic order

- README.md
- debian/alternc.preinst
- debian/alternc.templates
Since the upgrade incurs data loss if the user has alternc-ssl installed, we attempt to warn the user before continuing with the upgrade.
> Fixes #415: Add upgrade notice when installing 3.5 if upgrading from a version less than 3.3.12

- debian/alternc.postinst
- src/compress_logs.sh
- src/delete_logs.sh
Fixes #536
compress_logs.sh and delete_logs.sh use the same DAYS variable, which forbid customization in local.sh without affecting both housekeeping scripts at the same time.
This commit rename both variable to distinct and more explicit names.
> [scripts] LOGS_COMPRESS_DAYS and LOGS_DELETE_DAYS

- bureau/class/config.php
- bureau/class/functions.php
As explained in #605 , Mersenne Twister can generate token collision quickly.
We try to reduce this risk with :
* increase random seed using default behavior
* try at least 5 times before to break page home loading
close #605
> Issue 605 - Reduce csrf colission risk
