bureau/class/m_dom.php

Hi !
I've added support for .co on our servers, if you want the code, its all yours !
Super thanks !
G

Added support for .co, which has the same layout as .cc

---

jessie/alternc-ssl.install.php

in jessie there was no roundcube-ssl domain type

typo prevented roundcube-ssl domaintype to be created

---

etc/alternc/templates/alternc/apache2.conf

Devrait régler les problèmes d'accès un peu partout. Comme rapporté ici #265 
Permet la compatibilité avec apache2.4 (celui de jessie et stretch)

pour permettre la compatibilite avec apache2.4

---

etc/alternc/templates/bind/named.conf.options

Fix #294:  bind allow-transfer on internal ipv6

---

bureau/class/m_ssl.php

Fix condition check for replacing the chainfile statement in vhost

---

install/alternc.install

Deploy alternc.conf apache configuration

---

bureau/class/m_bind.php

Do not add bind entries for sub domaines marked for deletion

---

etc/alternc/templates/apache2/vhost-both.conf
etc/alternc/templates/apache2/vhost-http.conf
etc/alternc/templates/apache2/vhost-https.conf

This allows apps to override vhose MultiViews option in .htaccess. I needed this for nextcloud.

allow override of MultiViews option in .htaccess

---

bureau/class/m_dom.php

Fix domain deletion query

---

etc/alternc/templates/apache2/vhost-http.conf

"on hosting" seemed a francism

[fix] apache2 template: typo and rephrase comment

---

bureau/admin/dom_edit.php
bureau/class/functions.php
bureau/locales/de_DE/LC_MESSAGES/alternc
bureau/locales/de_DE/LC_MESSAGES/messages.po
bureau/locales/en_US/LC_MESSAGES/alternc
bureau/locales/en_US/LC_MESSAGES/messages.po
bureau/locales/es_ES/LC_MESSAGES/alternc
bureau/locales/es_ES/LC_MESSAGES/messages.po
bureau/locales/es_ES/LC_MESSAGES/ssl.po
bureau/locales/fr_FR/LC_MESSAGES/alternc
bureau/locales/fr_FR/LC_MESSAGES/messages.po
bureau/locales/it_IT/LC_MESSAGES/alternc
bureau/locales/it_IT/LC_MESSAGES/messages.po
bureau/locales/messages.pot
bureau/locales/nl_NL/LC_MESSAGES/alternc
bureau/locales/nl_NL/LC_MESSAGES/messages.po
bureau/locales/pt_BR/LC_MESSAGES/alternc
bureau/locales/pt_BR/LC_MESSAGES/messages.po
bureau/locales/pt_BR/LC_MESSAGES/ssl.po
lang/en_US.po
lang/nl_NL.po

fix minor typo

---

src/inotify_do_actions.sh
src/inotify_update_domains.sh

add exit 1 to inotify scripts, goes around the serious incrond bug in debian

---

bureau/class/m_bind.php
bureau/class/m_dom.php

Filter generated bind configuration by current domain

---

bureau/class/db_mysql.php
bureau/class/m_action.php
bureau/class/m_dom.php
phpunit/tests/_datasets/actions-began.yml
phpunit/tests/_datasets/actions-purgeable.yml
phpunit/tests/_datasets/actions-ready.yml
phpunit/tests/bureau/class/m_domTest.php

Hi,
here are a few trivial fixes for the 3.5 branch in order to have unit tests pass.

unittest fixes

---

etc/alternc/templates/opendkim.conf

* Force opendkim to be ran with a specific user
close #404

Use same user to create and read dkim key

---

etc/alternc/templates/dovecot/conf.d/95_alternc.conf

* Don't overwrite existing plugins list
* Alternc need to add its need without remove anything
close #568

Conserve all dovecot plugins

---

bureau/admin/about.php
bureau/admin/adm_slavedns.php
bureau/class/config.php
install/upgrades/3.5.0.5.php

Update help url 

---

src/fixperms_mail.sh

[mail] fixing 582

---

install/upgrades/3.5.0.2.php
install/upgrades/3.5.0.2.sql
install/upgrades/3.5.0.6.sql

* We can't have a DKIM declaration at root domain, a selector is required

Affect selector to all orphan DKIM declaration

---

bureau/class/m_admin.php

when allowed (typically when not changing a password or creating a mail alias)
Fixes #614

[fix] checkPolicy not handling empty password properly 

---

bureau/class/m_mail.php

* Prevent Integrity constraint violation
close #633

Issue 633 : Delete alias and mailbox before address
